In [17]:
from google.colab import drive 

In [18]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [19]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/Data.csv')

In [20]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [21]:
df.shape

(10, 4)

In [22]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [25]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [26]:
df

Country        Age   Salary Purchased
0   France  44.000000  72000.0        No
1    Spain  27.000000  48000.0       Yes
2  Germany  30.000000  54000.0        No
3    Spain  38.000000  61000.0        No
4  Germany  40.000000      NaN       Yes
5   France  35.000000  58000.0       Yes
6    Spain  38.777778  52000.0        No
7   France  48.000000  79000.0       Yes
8  Germany  50.000000  83000.0        No
9   France  37.000000  67000.0       Yes

In [28]:
df['Salary']=df['Salary'].fillna(df['Salary'].median())

In [29]:
df.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer
myimputer=SimpleImputer(missing_values=np.nan,strategy='median')

myimputer.fit(x[:,1:3])

x[:,1:3]=myimputer.transform(x[:,1:3])

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [32]:
# .values will convert it into Numpy, if you want dataframe than dont right .value
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [35]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()

x[:,0]=le.fit_transform(x[:,0])

In [ ]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 61000.0],
       [0, 35.0, 58000.0],
       [2, 38.0, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

One_hot_Encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(transformers=[('encode',OneHotEncoder(),[0])],remainder='passthrough')

In [ ]:
x=ct.fit_transform(x)

#splitting data

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.2,stratify=y)

In [ ]:
X_test

array([[0.0, 1.0, 0.0, 40.0, 61000.0],
       [0.0, 0.0, 1.0, 38.0, 52000.0]], dtype=object)

# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
X_train

array([[0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0]], dtype=object)

In [ ]:
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])


In [ ]:
X_train

array([[0.0, 1.0, 0.0, 1.4810949949635102, 1.5511947816430594],
       [1.0, 0.0, 0.0, -0.21158499928050145, 0.15293469678171007],
       [1.0, 0.0, 0.0, -0.4719973060872725, -0.6335866009527988],
       [1.0, 0.0, 0.0, 0.6998580745431972, 0.5898909733008817],
       [0.0, 0.0, 1.0, -1.5136465333143565, -1.5074991539911422],
       [0.0, 1.0, 0.0, -1.1230280731042, -0.9831516221681362],
       [1.0, 0.0, 0.0, 1.2206826881567392, 1.201629760427722],
       [0.0, 0.0, 1.0, -0.08137884587711594, -0.3714128350412959]],
      dtype=object)